feat: to be able to proxify up to 10 distinct public or protected url/path

diff --git a/image/httpd-foreground b/image/httpd-foreground
--- a/image/httpd-foreground
+++ b/image/httpd-foreground
@@ -7,18 +7,46 @@ export RENATER_SP_ENTITY_ID=${RENATER_SP_ENTITY_ID}
 export RENATER_SP_ADMIN_MAIL=${RENATER_SP_ADMIN_MAIL:='admin@exemple.fr'}
 export RENATER_SP_HTTPD_SERVER_NAME=${RENATER_SP_HTTPD_SERVER_NAME}
 export RENATER_SP_HTTPD_LOG_LEVEL=${RENATER_SP_HTTPD_LOG_LEVEL:='info ssl:warn'}
-export RENATER_SP_HTTPD_PROTECTED_PATH=${RENATER_SP_HTTPD_PROTECTED_PATH}
-export RENATER_SP_HTTPD_PUBLIC_PROXY_TO=${RENATER_SP_HTTPD_PUBLIC_PROXY_TO}
-export RENATER_SP_HTTPD_PROTECTED_PROXY_TO=${RENATER_SP_HTTPD_PROTECTED_PROXY_TO}
+for i in 0 1 2 3 4 5 6 7 8 9
+do
+	export RENATER_SP_HTTPD_PUBLIC_PATH_${i}=${RENATER_SP_HTTPD_PUBLIC_PATH_${i}}
+	export RENATER_SP_HTTPD_PUBLIC_PROXY_TO_${i}=${RENATER_SP_HTTPD_PUBLIC_PROXY_TO_${i}}
+	export RENATER_SP_HTTPD_PROTECTED_PATH_${i}=${RENATER_SP_HTTPD_PROTECTED_PATH_${i}}
+	export RENATER_SP_HTTPD_PROTECTED_PROXY_TO_${i}=${RENATER_SP_HTTPD_PROTECTED_PROXY_TO_${i}}
+done
+
 # for easy debug: display the container parameters at startup
-env | grep RENATER_SP_
+set | grep -e "^RENATER_SP_"
+
 # check for mandatory parameters
 SEE_ALSO_LINK="Have a look to https://github.com/abes-esr/docker-shibboleth-sp/blob/main/.env-dist for values examples."
 if [ -z ${RENATER_SP_ENTITY_ID} ]; then echo "Error: RENATER_SP_ENTITY_ID is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
 if [ -z ${RENATER_SP_HTTPD_SERVER_NAME} ]; then echo "Error: RENATER_SP_HTTPD_SERVER_NAME is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
-if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH} ]; then echo "Error: RENATER_SP_HTTPD_PROTECTED_PATH is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
-if [ -z ${RENATER_SP_HTTPD_PUBLIC_PROXY_TO} ]; then echo "Error: RENATER_SP_HTTPD_PUBLIC_PROXY_TO is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
-if [ -z ${RENATER_SP_HTTPD_PROTECTED_PROXY_TO} ]; then echo "Error: RENATER_SP_HTTPD_PROTECTED_PROXY_TO is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_0} ]; then echo "Error: RENATER_SP_HTTPD_PUBLIC_PATH_0 is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PROXY_TO_0} ]; then echo "Error: RENATER_SP_HTTPD_PUBLIC_PROXY_TO_0 is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_0} ]; then echo "Error: RENATER_SP_HTTPD_PROTECTED_PATH_0 is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PROXY_TO_0} ]; then echo "Error: RENATER_SP_HTTPD_PROTECTED_PROXY_TO_0 is a mandatory parameter. ${SEE_ALSO_LINK}" && exit 1 ; fi
+
+# update vhosts depending on public and protected path
+cp -f /usr/local/apache2/conf/extra/httpd-vhosts.conf.orig /usr/local/apache2/conf/extra/httpd-vhosts.conf
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_1} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_1.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_2} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_2.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_3} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_3.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_4} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_4.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_5} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_5.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_6} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_6.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_7} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_7.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_8} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_8.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PUBLIC_PATH_9} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PUBLIC_PATH_9.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_1} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_1.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_2} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_2.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_3} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_3.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_4} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_4.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_5} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_5.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_6} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_6.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_7} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_7.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_8} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_8.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
+if [ -z ${RENATER_SP_HTTPD_PROTECTED_PATH_9} ]; then  sed -i 's#^.*RENATER_SP_HTTPD_PROTECTED_PATH_9.*$##g' /usr/local/apache2/conf/extra/httpd-vhosts.conf ; fi
 
 # instanciates shibboleth2.xml from it's template
 cp -f /etc/shibboleth/shibboleth2.orig.xml /etc/shibboleth/shibboleth2.xml
